version: "3"
services:
  web1:
    image: nginx
    container_name: web1_container
    ports:
      - "8001:80"
    volumes:
      - "/home/cjm/docker/nginx/web1:/usr/share/nginx/html"
    networks:
      web_net:
        ipv4_address: 192.158.1.11
  web2:
    image: nginx
    container_name: web2_container
    ports:
      - "8002:80"
    volumes:
      - "/home/cjm/docker/nginx/web2:/usr/share/nginx/html"
    networks:
      web_net:
        ipv4_address: 192.158.1.12
  mynginx:
    image: nginx
    container_name: nginx_container
    ports:
      - "9009:80"
    volumes:
      - "/home/cjm/docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf"
    networks:
      web_net:
        ipv4_address: 192.158.1.10

networks:
  web_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.158.1.0/24

 
